import type { Metadata } from "next";
import { Cairo, Poppins } from "next/font/google";
import "@/styles/globals.css";
import { BackgroundCursor } from "@/components";

const inter = Poppins({ weight: ["100", "200", "300", "400", "500", "700", "600", "900", "800"], subsets: ["latin"], variable: "--font-main" });
// const CairoFont = Cairo({ variable: "--font-main", subsets: ["arabic", "latin"] });

export const metadata: Metadata = {
  title: "OSMX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <BackgroundCursor>{children}</BackgroundCursor>
      </body>
    </html>
  );
}
